### ISSUE TITLE
Reintegration of existing tool icons

### ISSUE THREAD

**Issue by simonrepp** [pasbi/ommpfritt#115]
I see that the rasterized icons are now generated from omm (which is cool), however as the tool icons do not yet exist in the omm-based icons file their deletion in https://github.com/pasbi/ommpfritt/commit/8e05821a130cdcad3f9523b1c208fa5d371ff52b essentially wiped them from the interface (which is a bit of a bummer for the user, and for me as I spent time on them).

If the pre-buillt and the JIT-built icons can coexist it'd probably be trivial to revert the deletion of the tool icons specifically, otherwise someone (TM) will need to port them from svg to omm, probably manually until #15 hits the stage.

**Comment by pasbi** [comment]
I was hoping that the deletion motivated someone to create the icons in omm, but that was maybe a bit too naive :laughing: .
Yes, it's trivial to restore the deletion (otherwise I wouldn't have deleted them in the first place).
It should be trivial to implement coexisting png- and JIT icons, I will look into this asap (i.e., not before next week).

**Comment by simonrepp** [comment]
Cool thanks!
