### ISSUE TITLE
Image (object) feature not found

### ISSUE THREAD

**Issue by simonrepp** [pasbi/ommpfritt#145]
According to the readme there is an image (object) feature:

> * image: load JPG, PNG, SVG, PDF as object

I looked hard but did not find any way to get an external raster image onto the canvas.

Does it exist or is there any other way to get this done? (specifically I'm trying to get a reference backdrop image into the viewport so I can rebuild something that only exists as pixels with omm's vector tools)

**Comment by pasbi** [comment]
it used to be there, I'm afraid the docs are out of date.
The problem is, that the size of the image object is quite hard to determine.
But knowing the size is important for features like the bounding box tools.

Iirc, this is why I have removed the image object for now (there were other minor issues).

Question is, if there is room for an Image "Object" because displaying images is actually the responsibility of the texture (i.e., node system).
Afaik, there is no Image-Node currently, but it is on my to-do list.

Many tools I know (Cinema 4D, Blender, ...) have a shortcut to display an image on the canvas directly (usually not visible in render mode).
That could be a nice and easy-to-implement feature (PR/feature request welcome).

**Comment by simonrepp** [comment]
I see, thanks!

I get your notion behind questioning the image object entirely in the context of the existing (or anyway for images planned) node-based approach. Ultimately that's not an easy one to answer, my spontaneous thought on this however is that if there is really only a node-based approach to having raster images show up it would eventually (mid/long-term) probably be important to offer some workflow that transparently sets up the nodes in the background (i.e. from a user POV there is only "drag image onto canvas > image appears"), so that this does not get tedious when multiple images are to be set up rapidly in succession.

With respect to the near future, I'd say whichever image variant you yourself primarily had on your personal roadmap for omm should be the first one to land. If that shall be a helper/reference/guide-like viewport-only image I can gladly open a ticket and provide some notes that maybe come to mind looking at how other 2/3d suites implement it.
