### ISSUE TITLE
Instant crash on pressing Delete while using the 'Select objects' tool

### ISSUE THREAD

**Issue by simonrepp** [pasbi/ommpfritt#83]
When I press the `Delete` key while using the `Select objects` tool, a crash occurs (regardless of whether an object is selected or not).

Feel free to ignore if known and a longer story. :)

**Comment by pasbi** [comment]
The problem is two fold.
1. Delete is by default mapped to the 'Remove points' command.
2. You're deleting points in object mode, which will delete no points. In order to avoid creating an empty ReomvePointsCommand (which would mess up the undo stack), the application crashes.
Deleting objects is mapped to Ctrl+Del by default.

You can look up the key mapping: `Window` -> `Show key bindings dialog`

It's easy to add a conditional which tests if the command is empty and does nothing if so, rather than crashing.

**Comment by simonrepp** [comment]
:tada:
